modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="michrosia"
version="1.0.0"
displayName="Michrosia"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Blackout03"

[[dependencies.michrosia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




